global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'bid-command'
    metrics_path: /metrics
    static_configs:
      - targets: ['bid-command:8080']

  - job_name: 'bid-query'
    metrics_path: /metrics
    static_configs:
      - targets: ['bid-query:8080']
