openapi: 3.0.3
info:
  title: Bid Command Service API
  version: 1.0.0

servers:
  - url: http://localhost:8082

paths:
  /api/v1/bids/{auctionId}:
    post:
      summary: Place a bid on an auction
      description: >
        Place a new bid for a given auction.  
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: auctionId
          required: true
          schema:
            type: string
          description: ID of the auction to bid on
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlaceBidRequest"
      responses:
        '201':
          description: Bid accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaceBidResponse"
                headers:
                  X-Request-Id:
                    description: Echoes back the request ID, if not provided by the client, server generates one.
                    schema: { type: string }
        '400':
          description: Invalid request (e.g., missing fields)
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        '401':
          description: Unauthorized (missing or invalid JWT)
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        '409':
          description: Conflict (out-of-date version or duplicate)
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        '422':
          description: Bid rejected (below minimum increment, auction closed, etc.)
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807) Problem Details for HTTP APIs
    ProblemDetails:
      type: object
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          description: A URI reference [RFC3986] that identifies the problem type
          example: https://biddergod.com/problems/below-min-increment
        title:
          type: string
          description: A short, human-readable summary of the problem type
          example: Bid rejected below minimum increment
        status:
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem
          example: 4xx
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
          example: Invalid bid amount, 100.0. Minimum next bid is 102.5
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem
          format: uri
          example: /auctions/a_456/bids/b_789

    PlaceBidRequest:
      type: object
      required:
        - bidderId
        - amount
      properties:
        bidderId:
          type: string
          example: user_123
        amount:
          type: number
          format: double
          example: 101.5

    PlaceBidResponse:
      type: object
      required:
        - bidId
        - auctionId
        - bidderId
        - accepted
        - currentPrice
        - minNextBid
        - version
        - at
      properties:
        bidId:
          type: string
          example: b_789
        auctionId:
          type: string
          example: a_456
        bidderId:
          type: string
          example: user_123
        accepted:
          type: boolean
          example: true
        currentPrice:
          type: number
          format: double
          example: 101.5
        minNextBid:
          type: number
          format: double
          example: 102.5
        at:
          type: string
          format: date-time
          example: "2025-09-01T10:22:33Z"